<?php

use Krystal\Form\Element;

?>

<form>
	<div class="well clearfix">

        <?php echo Element::hidden('banner[id]', $banner->getId()); ?>
        <?php echo Element::hidden('banner[file]', $banner->getFile()); ?>
        
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
			<div class="col-lg-10">
                <?php echo Element::text('banner[name]', $banner->getName(), array('class' => 'form-control', 'placeholder' => $this->translate('Banner name'))); ?>
			</div>
		</div>
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('URL Link'); ?></label>
			<div class="col-lg-10">
                <?php echo Element::text('banner[link]', $banner->getLink(), array('class' => 'form-control', 'placeholder' => $this->translate('URL link when clicked'))); ?>
			</div>
		</div>
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('File'); ?></label>
			<div class="col-lg-10">
                <?php echo Element::file('file'); ?>
			</div>
		</div>
	</div>
	
	<?php if ($banner->getId()): ?>
	<button data-button="save" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>

	<?php else: ?>
	<button data-button="add" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
	
    <?php endif; ?>

	<button data-button="cancel" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>

</form>
