<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="btn-toolbar">
    <?php $this->loadPartial('menu', array(
        'items' => array(
            'Banner:Admin:Banner@addAction' => 'Add new banner',
            'Banner:Admin:Category@addAction' => 'Add new category'
        ),

        'actions' => array(
            'data' => $banners,
            'delete' => 'Banner:Admin:Banner@deleteAction'
        )
    )); ?>
</div>

<div class="card">
    <?php $this->loadPartial('items-per-page', array('caption' => 'Latest banners')); ?>

    <div class="table-responsive">
        <?= $this->widget(new GridViewWidget($banners, array(
            'pk' => 'id',
            'batch' => true,
            'tableClass' => 'table table-hover table-bordered table-striped table-sm',
            'rowAttributes' => array(
                'class' => function($banner){
                    return $banner->getExpired() ? 'danger' : 'success';
                }
            ),

            'columns' => array(
                array(
                    'column' => 'url_path',
                    'label' => 'Preview',
                    'value' => function($banner){
                        if ($banner->isImage()) {
                            return Element::image($banner->getUrlPath(), array('class' => 'img-fluid'));
                        } else if ($banner->isFlash()) {
                            return Element::object(400, 400, $banner->getUrlPath());
                        } else {
                            // Unknown type
                            return '';
                        }
                    }
                ),

                array(
                    'column' => 'name'
                ),

                array(
                    'column' => 'datetime',
                    'label' => 'Date and time of creation'
                ),

                array(
                    'column' => 'click_count',
                    'label' => 'Click count'
                ),

                array(
                    'column' => 'view_count',
                    'label' => 'Views'
                ),
                
                array(
                    'column' => 'expiration_type_text',
                    'label' => 'Expiration type',
                    'translateable' => true
                )
            ),

            'actions' => array(
                'edit' => function($banner){
                    return Icon::edit(
                        $this->url('Banner:Admin:Banner@editAction', $banner->getId()),
                        $this->translate('Edit this banner')
                    );
                },

                'remove' => function($banner){
                    return Icon::remove(
                        $this->url('Banner:Admin:Banner@deleteAction', $banner->getId()),
                        $this->translate('Remove this banner')
                    );
                }
            )
        ))); ?>
        
        <?php if (empty($banners)): ?>
        <div class="center-block">
            <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No banners'); ?></h2>
        </div>
        <?php endif; ?>
    </div>

    <?php $this->loadPartial('paginator'); ?>
</div>

<div class="card">
    <h2><?php $this->show('Categories'); ?> <small>(<?php echo count($categories); ?>)</small></h2>

    <?= $this->widget(new GridViewWidget($categories, array(
        'tableClass' => 'table table-hover table-bordered table-striped',
        'rowAttributes' => array(
            'class' => function($row) use ($categoryId){
                return $row['id'] == $categoryId ? 'table-info' : null;
            }
        ),
        'columns' => array(
            array(
                'column' => 'id',
                'label' => '#'
            ),

            array(
                'column' => 'name',
                'value' => function($row){
                    return Element::link($row['name'],  $this->url('Banner:Admin:Banner@categoryAction', $row['id']));
                }
            ),

            array(
                'column' => 'banners_count',
                'label' => 'Banners count'
            )
        ),

        'actions' => array(
            'edit' => function($row){
                return Icon::edit(
                    $this->url('Banner:Admin:Category@editAction', $row['id']),
                    $this->translate('Edit this category')
                );
            },

            'remove' => function($row){
                return Icon::remove(
                    $this->url('Banner:Admin:Category@deleteAction', $row['id']),
                    $this->translate('Remove this category')
                );
            }
        )
    ))); ?>

    <?php if (empty($categories)): ?>
    <div class="center-block">
        <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No categories'); ?></h2>
    </div>
    <?php endif; ?>
</div>