<?php

use Krystal\Form\Element;
defined('KRYSTAL') or die;

?>

<form data-group="category">
	<div class="well">
        <?php echo Element::hidden('category[id]', $category->getId()); ?>

        <div class="form-group">
			<label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
			<div class="col-lg-10">
                <?php echo Element::text('category[name]', $category->getName(), array('class' => 'form-control', 'placeholder' => $this->translate('Banner name'))); ?>
			</div>
		</div>
	</div>

	<?php if ($category->getId()): ?>
	<button data-button="save" data-url="<?php echo $this->url('Banner:Admin:Category@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>

	<?php else: ?>
	<button data-button="add" data-back-url="<?php echo $this->url('Banner:Admin:Category@editAction', null); ?>" data-url="<?php echo $this->url('Banner:Admin:Category@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
    <?php endif; ?>

    <button data-button="cancel" data-url="<?php echo $this->url('Banner:Admin:Banner@gridAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
</form>
