<?php

use Krystal\Form\Element;
defined('KRYSTAL') or die;

?>

<form class="card" data-group="category" autocomplete="off">
    <?php echo Element::hidden('category[id]', $category->getId()); ?>

    <div class="form-group">
        <label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
        <div class="col-lg-10">
            <?php echo Element::text('category[name]', $category->getName(), array('class' => 'form-control', 'placeholder' => $this->translate('Banner name'))); ?>
        </div>
    </div>

    <?php $this->loadPartial('actions', array(
        'new' => !$category->getId(),
        'add' => 'Banner:Admin:Category@addAction',
        'edit' => 'Banner:Admin:Category@editAction',
        'save' => 'Banner:Admin:Category@saveAction',
        'cancel' => 'Banner:Admin:Banner@gridAction'
    )); ?>
</form>